import type { SeedAchievement } from "./types";

/**
 * Achievements are checked against real counters after every completed action
 * (see src/lib/gamification.ts), so none of these can be earned by clicking
 * around — each one corresponds to something the user actually did.
 */

export const ACHIEVEMENTS: SeedAchievement[] = [
  {
    code: "first-step",
    title: "First Step",
    description: "Complete your very first daily step.",
    icon: "footprints",
    xp: 20,
    metric: "steps",
    threshold: 1,
  },
  {
    code: "streak-7",
    title: "7 Day Streak",
    description: "Show up seven days in a row.",
    icon: "flame",
    xp: 50,
    metric: "streak",
    threshold: 7,
  },
  {
    code: "streak-30",
    title: "30 Day Streak",
    description: "A full month without breaking the chain.",
    icon: "flame",
    xp: 150,
    metric: "streak",
    threshold: 30,
  },
  {
    code: "lessons-10",
    title: "10 Lessons",
    description: "Finish ten lessons with their quick checks.",
    icon: "book-open",
    xp: 60,
    metric: "lessons",
    threshold: 10,
  },
  {
    code: "lessons-25",
    title: "25 Lessons",
    description: "Twenty-five lessons completed.",
    icon: "graduation-cap",
    xp: 120,
    metric: "lessons",
    threshold: 25,
  },
  {
    code: "first-research",
    title: "First Research",
    description: "Complete a lesson from Research Fundamentals.",
    icon: "microscope",
    xp: 40,
    metric: "research",
    threshold: 1,
  },
  {
    code: "goal-setter",
    title: "Goal Setter",
    description: "Finish onboarding and get your roadmap.",
    icon: "target",
    xp: 25,
    metric: "steps",
    threshold: 0,
  },
  {
    code: "scout",
    title: "Opportunity Scout",
    description: "Save five opportunities worth coming back to.",
    icon: "bookmark",
    xp: 40,
    metric: "saved",
    threshold: 5,
  },
  {
    code: "first-application",
    title: "First Application",
    description: "Start tracking your first application.",
    icon: "rocket",
    xp: 80,
    metric: "applications",
    threshold: 1,
  },
  {
    code: "builder",
    title: "Builder",
    description: "Add your first project to your portfolio.",
    icon: "hammer",
    xp: 50,
    metric: "projects",
    threshold: 1,
  },
  {
    code: "portfolio-3",
    title: "Portfolio of Three",
    description: "Three projects in your portfolio.",
    icon: "layers",
    xp: 100,
    metric: "projects",
    threshold: 3,
  },
  {
    code: "steps-50",
    title: "50 Steps",
    description: "Fifty daily steps completed.",
    icon: "trending-up",
    xp: 100,
    metric: "steps",
    threshold: 50,
  },
  {
    code: "steps-100",
    title: "100 Steps",
    description: "One hundred steps into your 365.",
    icon: "award",
    xp: 200,
    metric: "steps",
    threshold: 100,
  },
  {
    code: "xp-1000",
    title: "1,000 XP",
    description: "Cross a thousand experience points.",
    icon: "zap",
    xp: 100,
    metric: "xp",
    threshold: 1000,
  },
  {
    code: "first-friend",
    title: "First Friend",
    description: "Add your first friend on 365step.",
    icon: "users",
    xp: 20,
    metric: "friends",
    threshold: 1,
  },
  {
    code: "first-battle",
    title: "First Battle",
    description: "Complete your first SAT battle against a friend.",
    icon: "swords",
    xp: 25,
    metric: "battles_played",
    threshold: 1,
  },
  {
    code: "battle-champion",
    title: "Battle Champion",
    description: "Win five SAT battles against friends.",
    icon: "swords",
    xp: 100,
    metric: "battles_won",
    threshold: 5,
  },
  {
    code: "daily-regular",
    title: "Daily Regular",
    description: "Complete the daily SAT challenge seven times.",
    icon: "calendar-check",
    xp: 60,
    metric: "daily_challenges",
    threshold: 7,
  },
];
