import type { SeedOpportunity } from "./types";

/**
 * The opportunity catalogue.
 *
 * ──────────────────────────── ACCURACY POLICY ────────────────────────────
 * `isDemo: false` entries are real, currently-running programmes, and
 * `officialUrl` points at the programme's own official page — never at an
 * aggregator. Descriptions stay at the level the organisers themselves state.
 *
 * `isDemo: true` entries are illustrative examples written for this demo. The
 * UI renders them with a visible "Demo example" badge and no outbound apply
 * link, so they can never be mistaken for a real programme.
 *
 * DEADLINES ARE INDICATIVE. Real application windows move every cycle, so
 * inventing exact dates would be asserting something false. Each entry instead
 * carries an offset in days from seed time: countdowns stay alive for the demo,
 * and every card and detail page tells the user to confirm the real date on the
 * official site. `sourceNote` records the provenance of each entry.
 * ─────────────────────────────────────────────────────────────────────────
 */

const CONFIRM = "Official programme. The deadline shown here is indicative for this demo — confirm the current date on the official site.";
const ROLLING = "Official programme. Applications run on a rolling or annually announced basis — check the official site for the current window.";

export const OPPORTUNITIES: SeedOpportunity[] = [
  // ───────────────────────────── school: research ─────────────────────────

  {
    slug: "mit-primes",
    title: "MIT PRIMES",
    organization: "Massachusetts Institute of Technology",
    type: "research",
    summary:
      "A year-long mathematics and computer science research programme for high school students, mentored by MIT researchers.",
    description:
      "PRIMES pairs high school students with MIT graduate students and researchers for a year of original research in mathematics, computer science and computational biology. Participants work through reading assignments in the spring and move into a research problem over the summer and following academic year, presenting their results at a conference. It is a serious research commitment rather than a summer camp, and several projects each year lead to papers.",
    audiences: ["school"],
    subjects: ["math", "cs", "data-science"],
    goalSlugs: ["start-research", "get-into-university", "win-competitions"],
    tags: ["Research", "Mathematics", "USA", "Free"],
    eligibility: [
      "High school students in the United States",
      "Strong background in mathematics or programming",
      "Able to commit several hours per week across the year",
      "Selection is by application including a problem set",
    ],
    country: "USA",
    location: "Cambridge, MA (with remote sections)",
    format: "hybrid",
    deadlineInDays: 46,
    cost: "Free",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://math.mit.edu/research/highschool/primes/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "research-science-institute",
    title: "Research Science Institute (RSI)",
    organization: "Center for Excellence in Education & MIT",
    type: "summer_program",
    summary:
      "Five weeks at MIT combining university-level coursework with an original research project. Fully funded.",
    description:
      "RSI brings around eighty students to MIT each summer for the first week of intensive STEM classes, followed by four weeks of mentored original research with scientists in the Boston area, and ends with written and oral presentations of their results. It is free to attend, including housing and meals, and is among the most selective science programmes for secondary students anywhere.",
    audiences: ["school"],
    subjects: ["physics", "math", "biology", "chemistry", "engineering", "cs"],
    goalSlugs: ["start-research", "get-into-university"],
    tags: ["Research", "STEM", "USA", "Fully funded"],
    eligibility: [
      "Students completing their junior year (Grade 11) at time of attendance",
      "Open to both US and international students",
      "Strong standardised test scores and science coursework",
      "Highly selective — application includes essays and recommendations",
    ],
    country: "USA",
    location: "Cambridge, MA",
    format: "in_person",
    deadlineInDays: 24,
    cost: "Free — housing and meals covered",
    minGrade: 11,
    maxGrade: 11,
    officialUrl: "https://www.cee.org/programs/research-science-institute",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "simons-summer-research",
    title: "Simons Summer Research Program",
    organization: "Stony Brook University",
    type: "research",
    summary:
      "Seven weeks working in a Stony Brook research group, ending with a poster symposium and a stipend.",
    description:
      "Simons Fellows join a faculty-led research team at Stony Brook University for the summer, take on responsibility for their own project within the group, and learn laboratory or computational techniques directly from graduate mentors. The programme ends with a written report and a poster presented at a closing symposium, and participants receive a stipend.",
    audiences: ["school"],
    subjects: ["biology", "chemistry", "physics", "engineering", "math", "medicine"],
    goalSlugs: ["start-research", "get-into-university", "build-portfolio"],
    tags: ["Research", "Lab experience", "USA", "Stipend"],
    eligibility: [
      "Current high school juniors (Grade 11)",
      "At least 16 years old by the start of the programme",
      "Residents of New York State are prioritised",
      "Requires a nomination letter from a science or maths teacher",
    ],
    country: "USA",
    location: "Stony Brook, NY",
    format: "in_person",
    deadlineInDays: 12,
    cost: "Free — stipend provided",
    minGrade: 11,
    maxGrade: 11,
    officialUrl: "https://www.stonybrook.edu/simons/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "stanford-simr",
    title: "Stanford Institutes of Medicine Summer Research Program",
    organization: "Stanford University School of Medicine",
    type: "research",
    summary:
      "Eight weeks of hands-on biomedical research in a Stanford lab, with a stipend for all participants.",
    description:
      "SIMR places high school students in Stanford medical school laboratories across institutes including cancer biology, immunology, neurobiology, bioengineering and genetics. Participants run a project under a mentor, attend lectures from Stanford faculty, and present a poster at the end of the summer. All admitted students receive a minimum stipend.",
    audiences: ["school"],
    subjects: ["biology", "medicine", "chemistry", "engineering", "data-science"],
    goalSlugs: ["start-research", "get-into-university"],
    tags: ["Research", "Biomedical", "USA", "Stipend"],
    eligibility: [
      "Current high school juniors or seniors (Grade 11–12)",
      "At least 16 years old by the programme start",
      "US citizens or permanent residents",
      "Bay Area applicants are prioritised for some institutes",
    ],
    country: "USA",
    location: "Stanford, CA",
    format: "in_person",
    deadlineInDays: 33,
    cost: "Free — stipend provided",
    minGrade: 11,
    maxGrade: 12,
    officialUrl: "https://simr.stanford.edu/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },

  // ─────────────────────────── school: summer programmes ───────────────────

  {
    slug: "mites-summer",
    title: "MITES Summer",
    organization: "Massachusetts Institute of Technology",
    type: "summer_program",
    summary:
      "Six weeks of rigorous STEM coursework at MIT for students from underrepresented backgrounds. No cost to attend.",
    description:
      "MITES Summer is a residential programme in which rising seniors take five demanding STEM and humanities courses on the MIT campus, alongside college and career guidance. It is free to participants, including travel, and is designed for students whose background is underrepresented in science and engineering or who face barriers to accessing advanced STEM preparation.",
    audiences: ["school"],
    subjects: ["engineering", "physics", "math", "cs", "biology"],
    goalSlugs: ["get-into-university", "build-portfolio"],
    tags: ["STEM", "USA", "Fully funded", "Access"],
    eligibility: [
      "Rising high school seniors (entering Grade 12)",
      "US citizens or permanent residents",
      "Strong academic record in maths and science",
      "Priority to students underrepresented in STEM or facing access barriers",
    ],
    country: "USA",
    location: "Cambridge, MA",
    format: "in_person",
    deadlineInDays: 8,
    cost: "Free — travel and housing covered",
    minGrade: 11,
    maxGrade: 12,
    officialUrl: "https://mites.mit.edu/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "yale-young-global-scholars",
    title: "Yale Young Global Scholars",
    organization: "Yale University",
    type: "summer_program",
    summary:
      "A two-week academic enrichment programme at Yale for secondary students from around the world.",
    description:
      "YYGS runs interdisciplinary summer sessions on the Yale campus across themes such as science and engineering innovation, politics and economics, and literature and philosophy. Students attend lectures by Yale faculty, work in small discussion seminars, and complete a capstone group project. Need-based financial aid is available, including full scholarships.",
    audiences: ["school"],
    subjects: ["engineering", "physics", "economics", "social-sciences", "humanities", "environment"],
    goalSlugs: ["get-into-university", "career-skills"],
    tags: ["Summer school", "International", "USA", "Financial aid"],
    eligibility: [
      "Currently in Grade 10 or 11 (or international equivalent)",
      "Open to students from any country",
      "Instruction is in English",
      "Need-based aid available up to full cost",
    ],
    country: "USA",
    location: "New Haven, CT",
    format: "in_person",
    deadlineInDays: 61,
    cost: "Tuition with need-based financial aid",
    minGrade: 10,
    maxGrade: 11,
    officialUrl: "https://globalscholars.yale.edu/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "harvard-secondary-school-program",
    title: "Harvard Summer School — Secondary School Program",
    organization: "Harvard University",
    type: "summer_program",
    summary:
      "Take genuine Harvard college courses for credit during the summer, on campus or online.",
    description:
      "The Secondary School Program lets high school students enrol in Harvard Summer School courses alongside undergraduates and earn college credit. Students choose from a wide catalogue across sciences, humanities and social sciences, and can attend residentially, commuting or online. Financial aid is available for students who qualify.",
    audiences: ["school"],
    subjects: ["humanities", "social-sciences", "biology", "cs", "economics", "math"],
    goalSlugs: ["get-into-university", "career-skills"],
    tags: ["College credit", "USA", "Online option"],
    eligibility: [
      "Students aged roughly 16–19 who have completed Grade 10 or above",
      "Open to international students",
      "Residential, commuting and online options",
      "Need-based financial aid available",
    ],
    country: "USA",
    location: "Cambridge, MA / online",
    format: "hybrid",
    deadlineInDays: 74,
    cost: "Paid — financial aid available",
    minGrade: 10,
    maxGrade: 12,
    officialUrl: "https://summer.harvard.edu/high-school-programs/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },

  // ───────────────────────────── school: olympiads ─────────────────────────

  {
    slug: "international-mathematical-olympiad",
    title: "International Mathematical Olympiad",
    organization: "IMO Foundation",
    type: "olympiad",
    summary:
      "The world championship of secondary school mathematics. Entry is through your national olympiad.",
    description:
      "The IMO is the oldest and most prestigious of the international science olympiads, with teams of up to six students from over a hundred countries solving six proof-based problems across two days. You do not apply to the IMO directly: each country selects its team through a national olympiad sequence, so the practical first step is finding and entering your national competition.",
    audiences: ["school"],
    subjects: ["math"],
    goalSlugs: ["win-competitions", "get-into-university"],
    tags: ["Olympiad", "Mathematics", "International", "Free"],
    eligibility: [
      "Secondary school students under 20 who have not entered university",
      "Selected via your own country's national mathematical olympiad",
      "Team size of up to six per country",
      "No direct application to the IMO itself",
    ],
    country: "International",
    location: "Rotates annually",
    format: "in_person",
    deadlineInDays: null,
    cost: "Free",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://www.imo-official.org/",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 3,
  },
  {
    slug: "international-olympiad-informatics",
    title: "International Olympiad in Informatics",
    organization: "IOI",
    type: "olympiad",
    summary:
      "The world championship of competitive programming for secondary students, entered via your national olympiad.",
    description:
      "The IOI is the premier algorithmic programming competition for school students, with national teams of up to four solving algorithmic problems over two contest days. As with the IMO, selection runs through each country's national informatics olympiad, so the route in is your national contest and its training programme.",
    audiences: ["school"],
    subjects: ["cs", "math"],
    goalSlugs: ["win-competitions", "get-into-university"],
    tags: ["Olympiad", "Programming", "International", "Free"],
    eligibility: [
      "Secondary school students, selected by their country",
      "Team size of up to four per country",
      "Entry through your national informatics olympiad",
      "Strong algorithms and data structures background expected",
    ],
    country: "International",
    location: "Rotates annually",
    format: "in_person",
    deadlineInDays: null,
    cost: "Free",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://ioinformatics.org/",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 3,
  },
  {
    slug: "usa-physics-olympiad",
    title: "US Physics Team / Physics Olympiad",
    organization: "American Association of Physics Teachers",
    type: "olympiad",
    summary:
      "The selection route to the International Physics Olympiad, starting with the F=ma exam.",
    description:
      "AAPT runs the competition sequence that selects the US Physics Team: students first sit the F=ma mechanics exam, top scorers advance to the USA Physics Olympiad exam, and around twenty are invited to a training camp from which the five-member international team is chosen. Registration is through a school or an approved test centre.",
    audiences: ["school"],
    subjects: ["physics", "math", "engineering"],
    goalSlugs: ["win-competitions", "get-into-university"],
    tags: ["Olympiad", "Physics", "USA"],
    eligibility: [
      "High school students in the United States",
      "Registration through a school or approved centre",
      "Begins with the F=ma exam",
      "Mechanics and calculus-level problem solving required",
    ],
    country: "USA",
    location: "USA (exam centres) then training camp",
    format: "in_person",
    deadlineInDays: 27,
    cost: "Small exam fee",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://www.aapt.org/physicsteam/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },

  // ──────────────────────────── school: competitions ──────────────────────

  {
    slug: "regeneron-isef",
    title: "Regeneron International Science and Engineering Fair",
    organization: "Society for Science",
    type: "competition",
    summary:
      "The world's largest pre-college science competition. Qualify through an affiliated regional fair.",
    description:
      "ISEF brings together around 1,700 finalists from roughly 70 countries to present original research across some twenty categories, competing for several million dollars in awards. You cannot enter ISEF directly: students qualify by winning at an affiliated regional or national fair, which makes finding your local affiliated fair the actual first step.",
    audiences: ["school"],
    subjects: ["physics", "biology", "chemistry", "engineering", "cs", "environment", "math", "medicine"],
    goalSlugs: ["start-research", "win-competitions", "get-into-university", "build-portfolio"],
    tags: ["Competition", "Research", "International", "Awards"],
    eligibility: [
      "Students in Grades 9–12 (or equivalent), under 20",
      "Must qualify through an ISEF-affiliated regional or national fair",
      "Original research project required",
      "Projects involving human or vertebrate subjects need prior approval",
    ],
    country: "International",
    location: "USA (host city rotates)",
    format: "in_person",
    deadlineInDays: 118,
    cost: "Free for finalists — regional fair rules vary",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://www.societyforscience.org/isef/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "regeneron-science-talent-search",
    title: "Regeneron Science Talent Search",
    organization: "Society for Science",
    type: "competition",
    summary:
      "The oldest science and mathematics competition for US high school seniors, with substantial scholarships.",
    description:
      "The Science Talent Search asks graduating seniors to submit an original independent research project, which is judged on scientific rigour and on the student's own understanding of it. Forty finalists are invited to Washington DC for a week of judging and public exhibition, competing for top awards in the hundreds of thousands of dollars.",
    audiences: ["school"],
    subjects: ["physics", "biology", "chemistry", "engineering", "cs", "math", "medicine", "social-sciences"],
    goalSlugs: ["start-research", "win-competitions", "get-into-university"],
    tags: ["Competition", "Research", "USA", "Scholarship"],
    eligibility: [
      "High school seniors (Grade 12) in the United States",
      "US citizens, or students attending US schools per programme rules",
      "Original independent research project required",
      "Submission includes the research report plus essays and recommendations",
    ],
    country: "USA",
    location: "Washington, DC (finals)",
    format: "in_person",
    deadlineInDays: 52,
    cost: "Free to enter",
    minGrade: 12,
    maxGrade: 12,
    officialUrl: "https://www.societyforscience.org/regeneron-sts/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "conrad-challenge",
    title: "Conrad Challenge",
    organization: "Conrad Foundation",
    type: "competition",
    summary:
      "A team innovation competition where students build a commercial solution to a real-world problem.",
    description:
      "Teams of two to five students choose a category — such as aerospace, energy, health, cyber-technology or education — and develop an innovation addressing a genuine problem, submitting a business plan and pitch rather than only a prototype. The competition runs in stages across the academic year, ending with finalists presenting to judges at the Innovation Summit.",
    audiences: ["school"],
    subjects: ["engineering", "business", "cs", "environment", "medicine", "physics"],
    goalSlugs: ["win-competitions", "build-portfolio", "get-into-university"],
    tags: ["Competition", "Innovation", "International", "Teams"],
    eligibility: [
      "Students aged 13–18",
      "Teams of two to five, open internationally",
      "Requires a written innovation brief and business plan",
      "Adult coach or teacher advisor required",
    ],
    country: "International",
    location: "Online rounds, in-person finals in USA",
    format: "hybrid",
    deadlineInDays: 39,
    cost: "Entry fee per team, with fee waivers available",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://www.conradchallenge.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "diamond-challenge",
    title: "Diamond Challenge",
    organization: "University of Delaware Horn Entrepreneurship",
    type: "competition",
    summary:
      "A high school entrepreneurship competition with cash prizes for business and social-venture concepts.",
    description:
      "Teams submit a written concept for either a business venture or a social venture, with the strongest advancing to pitch live at the Diamond Challenge Summit. The programme provides a structured curriculum alongside the competition, which makes it a practical first entry point for students who have an idea but no business background.",
    audiences: ["school"],
    subjects: ["business", "economics", "social-sciences", "environment"],
    goalSlugs: ["win-competitions", "build-portfolio", "career-skills"],
    tags: ["Competition", "Entrepreneurship", "International", "Prizes"],
    eligibility: [
      "Students in Grades 9–12 (or equivalent), aged 14–18",
      "Teams of two to four",
      "Open internationally",
      "Business venture and social venture tracks",
    ],
    country: "International",
    location: "Online rounds, finals in USA",
    format: "hybrid",
    deadlineInDays: 21,
    cost: "Free to enter",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://diamondchallenge.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "technovation-girls",
    title: "Technovation Girls",
    organization: "Technovation",
    type: "competition",
    summary:
      "A global programme where girls build a working app or AI project addressing a community problem.",
    description:
      "Over a twelve-week season, teams identify a problem in their own community, build a mobile app or AI prototype to address it, and submit a pitch video and business plan. Teams are supported by volunteer mentors, and the curriculum assumes no prior programming experience, which makes it a realistic first technical project.",
    audiences: ["school"],
    subjects: ["cs", "data-science", "social-sciences", "business"],
    goalSlugs: ["build-portfolio", "win-competitions", "career-skills"],
    tags: ["Competition", "Coding", "International", "Free", "Mentored"],
    eligibility: [
      "Girls and non-binary students aged 8–18",
      "Teams of one to five with an adult mentor",
      "Open worldwide",
      "No prior coding experience required",
    ],
    country: "International",
    location: "Remote, with regional and global finals",
    format: "remote",
    deadlineInDays: 15,
    cost: "Free",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://www.technovation.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "first-robotics-competition",
    title: "FIRST Robotics Competition",
    organization: "FIRST",
    type: "competition",
    summary:
      "Build and compete with a large-scale robot in a season that runs alongside the school year.",
    description:
      "Teams of students, supported by mentors, design and build an industrial-scale robot in a six-week build period to compete in that season's game at regional and championship events. Beyond the engineering, teams handle fundraising, project management and outreach, and FIRST participants have access to a substantial pool of affiliated scholarships.",
    audiences: ["school"],
    subjects: ["engineering", "cs", "physics", "math"],
    goalSlugs: ["build-portfolio", "win-competitions", "get-into-university"],
    tags: ["Robotics", "Engineering", "International", "Teams", "Scholarships"],
    eligibility: [
      "Students in Grades 9–12 (or equivalent)",
      "Participation through a registered school or community team",
      "Open in many countries worldwide",
      "Team registration fees apply, with grants available",
    ],
    country: "International",
    location: "Regional events worldwide",
    format: "in_person",
    deadlineInDays: 5,
    cost: "Team registration fee — grants available",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://www.firstinspires.org/robotics/frc",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },

  // ───────────────────────── university: research & internships ───────────

  {
    slug: "cern-summer-student",
    title: "CERN Summer Student Programme",
    organization: "CERN",
    type: "internship",
    summary:
      "Eight to thirteen weeks working on a real project at CERN, with a full lecture programme alongside.",
    description:
      "Summer students join a CERN research or engineering team and take on a project in physics, computing, engineering or data analysis, while attending a dedicated lecture series given by CERN scientists and visiting the accelerator and experiment facilities. Participants receive a subsistence allowance and travel support.",
    audiences: ["university"],
    subjects: ["physics", "cs", "engineering", "math", "data-science"],
    goalSlugs: ["find-internship", "start-research", "career-skills"],
    tags: ["Research", "Physics", "Switzerland", "Paid"],
    eligibility: [
      "Undergraduate or master's students in physics, engineering, computing or maths",
      "At least three years of university study completed for most streams",
      "Nationals of CERN member and associate member states are prioritised",
      "Good working knowledge of English",
    ],
    country: "Switzerland",
    location: "Geneva",
    format: "in_person",
    deadlineInDays: 41,
    cost: "Paid — allowance and travel support",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://careers.cern/summer",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "daad-rise-germany",
    title: "DAAD RISE Germany",
    organization: "German Academic Exchange Service (DAAD)",
    type: "research",
    summary:
      "Summer research internships in German university and research institute labs, with a monthly stipend.",
    description:
      "RISE Germany places undergraduates from outside Germany into research groups for two to three months over the summer, working with a doctoral student mentor on a defined project in the natural sciences, engineering or related fields. Students browse and apply to specific posted projects, and DAAD provides a monthly stipend plus travel and insurance support.",
    audiences: ["university"],
    subjects: ["physics", "biology", "chemistry", "engineering", "cs", "environment", "data-science"],
    goalSlugs: ["start-research", "find-internship", "career-skills"],
    tags: ["Research", "Germany", "Paid", "Summer"],
    eligibility: [
      "Undergraduates enrolled outside Germany",
      "Have completed at least two years of study",
      "Studying biology, chemistry, physics, earth sciences, engineering or computing",
      "Working knowledge of English; German is not required",
    ],
    country: "Germany",
    location: "Universities and institutes across Germany",
    format: "in_person",
    deadlineInDays: 68,
    cost: "Paid — monthly stipend plus travel support",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://www.daad.de/rise/en/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "eth-zurich-summer-research",
    title: "ETH Zurich Summer Research Fellowship",
    organization: "ETH Zurich",
    type: "research",
    summary:
      "A two-month paid research placement in an ETH Zurich group for undergraduates in computer science and related fields.",
    description:
      "The fellowship funds undergraduate and early master's students to spend the summer on a research project in an ETH Zurich institute, working alongside a supervisor and doctoral students. Fellows receive a salary covering living costs in Zurich, and the programme is aimed at students seriously considering a research career.",
    audiences: ["university"],
    subjects: ["cs", "data-science", "math", "engineering"],
    goalSlugs: ["start-research", "find-internship"],
    tags: ["Research", "Switzerland", "Paid", "Computer science"],
    eligibility: [
      "Undergraduate or early master's students",
      "Typically at least two years of university study completed",
      "Strong academic record in a relevant field",
      "Applications are made to the programme, which matches fellows to groups",
    ],
    country: "Switzerland",
    location: "Zurich",
    format: "in_person",
    deadlineInDays: 30,
    cost: "Paid — salary covering living costs",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://ethz.ch/en/studies/summer-research-fellowship.html",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },
  {
    slug: "google-summer-of-code",
    title: "Google Summer of Code",
    organization: "Google Open Source",
    type: "internship",
    summary:
      "Get paid to write code for an open source organisation over the summer, mentored and remote.",
    description:
      "Contributors choose an open source organisation from the accepted list, discuss a project with its mentors, and submit a proposal. Accepted contributors spend the summer building their project with mentor support and receive a stipend. Because the work is public and the mentorship is real, it doubles as one of the strongest portfolio pieces available remotely.",
    audiences: ["university", "graduate"],
    subjects: ["cs", "data-science", "engineering"],
    goalSlugs: ["find-internship", "build-portfolio", "career-skills"],
    tags: ["Open source", "Remote", "Paid", "Mentored"],
    eligibility: [
      "18 or older at time of registration",
      "New to open source contribution, or a beginner contributor",
      "Not restricted to enrolled students",
      "Eligible to receive payments in a supported country",
    ],
    country: "Remote",
    location: "Remote, worldwide",
    format: "remote",
    deadlineInDays: 57,
    cost: "Paid — stipend",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://summerofcode.withgoogle.com/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "google-step-internship",
    title: "Google STEP Internship",
    organization: "Google",
    type: "internship",
    summary:
      "A twelve-week software engineering internship designed for first and second year undergraduates.",
    description:
      "STEP is Google's internship for students early in their degree, pairing participants with a mentor and a host team to work on a real engineering project alongside a cohort of other STEP interns. It exists precisely because most software internships assume more experience than a first or second year student has, and it is paid.",
    audiences: ["university"],
    subjects: ["cs", "engineering", "data-science"],
    goalSlugs: ["find-internship", "career-skills"],
    tags: ["Internship", "Software", "Paid", "Early undergrad"],
    eligibility: [
      "First or second year undergraduate students",
      "Pursuing a degree in computer science or a related technical field",
      "Some programming experience in one or more languages",
      "Availability varies by country and office",
    ],
    country: "Multiple",
    location: "Google offices worldwide",
    format: "hybrid",
    deadlineInDays: 19,
    cost: "Paid",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://buildyourfuture.withgoogle.com/programs/step",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "erasmus-plus",
    title: "Erasmus+ Student Mobility",
    organization: "European Commission",
    type: "exchange",
    summary:
      "Study or do a traineeship at a partner university abroad with an EU grant towards costs.",
    description:
      "Erasmus+ funds study periods and traineeships abroad for students at participating higher education institutions, typically from two to twelve months, with a grant contributing to travel and living costs. Applications are made through your own university's international office rather than centrally, which is the step most students miss.",
    audiences: ["university", "graduate"],
    subjects: ["engineering", "cs", "economics", "humanities", "social-sciences", "business", "environment"],
    goalSlugs: ["career-skills", "get-into-university", "find-internship"],
    tags: ["Exchange", "Europe", "Grant", "Study abroad"],
    eligibility: [
      "Enrolled at a participating higher education institution",
      "Apply through your own university's international office",
      "Study periods and traineeships from 2 to 12 months",
      "Grant amount varies by destination country",
    ],
    country: "Europe",
    location: "Partner universities across Europe and beyond",
    format: "in_person",
    deadlineInDays: 95,
    cost: "Grant-supported",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 2,
  },
  {
    slug: "hult-prize",
    title: "Hult Prize",
    organization: "Hult Prize Foundation",
    type: "competition",
    summary:
      "A global student social-enterprise competition with a one million dollar prize for the winning team.",
    description:
      "Student teams build a social enterprise addressing that year's challenge, progressing through on-campus rounds, regional summits and an accelerator to a global final. The programme is aimed at students who want to build something rather than write about it, and the structure gives teams a clear set of deadlines to work towards across the year.",
    audiences: ["university", "graduate"],
    subjects: ["business", "economics", "social-sciences", "environment"],
    goalSlugs: ["win-competitions", "build-portfolio", "career-skills"],
    tags: ["Competition", "Social enterprise", "International", "Prize"],
    eligibility: [
      "Currently enrolled university students, undergraduate or postgraduate",
      "Teams of three to four",
      "Open worldwide",
      "Free to enter at the campus round",
    ],
    country: "International",
    location: "Campus rounds, regional summits, global final",
    format: "hybrid",
    deadlineInDays: 84,
    cost: "Free to enter",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://www.hultprize.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 2,
  },

  // ─────────────────────── graduate: scholarships & fellowships ───────────

  {
    slug: "chevening-scholarships",
    title: "Chevening Scholarships",
    organization: "UK Foreign, Commonwealth & Development Office",
    type: "scholarship",
    summary:
      "Fully funded one-year master's study in the UK for emerging leaders from eligible countries.",
    description:
      "Chevening funds a one-year taught master's at any UK university, covering tuition, a living stipend, flights and additional allowances. Selection weighs leadership potential and a clear plan for how the degree will be applied on returning home at least as heavily as academic record, and applicants must have work experience.",
    audiences: ["graduate", "university"],
    subjects: ["social-sciences", "economics", "business", "environment", "engineering", "humanities", "data-science"],
    goalSlugs: ["career-skills", "get-into-university"],
    tags: ["Scholarship", "UK", "Master's", "Fully funded"],
    eligibility: [
      "Citizen of a Chevening-eligible country",
      "Hold an undergraduate degree qualifying you for UK postgraduate study",
      "At least two years (2,800 hours) of work experience",
      "Must return to your home country for at least two years afterwards",
    ],
    country: "United Kingdom",
    location: "Any UK university",
    format: "in_person",
    deadlineInDays: 36,
    cost: "Fully funded",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://www.chevening.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "fulbright-foreign-student",
    title: "Fulbright Foreign Student Program",
    organization: "US Department of State",
    type: "scholarship",
    summary:
      "Funded graduate study or research in the United States for students from participating countries.",
    description:
      "The Fulbright Foreign Student Program funds master's and doctoral study, or research, at US universities for candidates from over 160 countries. Applications are made through the Fulbright Commission or US Embassy in your own country, and each country sets its own priorities, deadlines and field restrictions — so the country page is the one that matters.",
    audiences: ["graduate", "university"],
    subjects: ["social-sciences", "economics", "engineering", "humanities", "environment", "medicine", "data-science"],
    goalSlugs: ["career-skills", "start-research", "get-into-university"],
    tags: ["Scholarship", "USA", "Graduate", "Fully funded"],
    eligibility: [
      "Citizen of a participating country",
      "Hold an undergraduate degree before the grant begins",
      "Apply through the Fulbright Commission or US Embassy in your country",
      "Country-specific requirements and deadlines apply",
    ],
    country: "USA",
    location: "US universities",
    format: "in_person",
    deadlineInDays: 71,
    cost: "Fully funded",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://foreign.fulbrightonline.org/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "knight-hennessy-scholars",
    title: "Knight-Hennessy Scholars",
    organization: "Stanford University",
    type: "fellowship",
    summary:
      "Full funding for any graduate degree at Stanford, plus a leadership development programme.",
    description:
      "Knight-Hennessy funds up to three years of any graduate degree at Stanford — from MA to PhD, MBA to MD — and adds a dedicated leadership development programme across the cohort. Applicants apply both to Knight-Hennessy and separately to their intended Stanford degree programme, and both applications must succeed.",
    audiences: ["graduate", "university"],
    subjects: ["engineering", "cs", "economics", "medicine", "social-sciences", "environment", "business", "humanities"],
    goalSlugs: ["career-skills", "start-research", "get-into-university"],
    tags: ["Fellowship", "USA", "Graduate", "Fully funded"],
    eligibility: [
      "Applying to a full-time Stanford graduate programme",
      "Received your first undergraduate degree within roughly the last seven years",
      "Open to citizens of any country",
      "Separate applications required to Knight-Hennessy and to the degree programme",
    ],
    country: "USA",
    location: "Stanford, CA",
    format: "in_person",
    deadlineInDays: 49,
    cost: "Fully funded",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://knight-hennessy.stanford.edu/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },
  {
    slug: "rhodes-scholarship",
    title: "Rhodes Scholarship",
    organization: "Rhodes Trust, University of Oxford",
    type: "scholarship",
    summary:
      "Fully funded postgraduate study at Oxford, selected by constituency around the world.",
    description:
      "The Rhodes Scholarship covers university and college fees plus a stipend for postgraduate study at Oxford, typically for two years. Selection happens within national or regional constituencies, each with its own deadline and process, and criteria weigh academic excellence alongside energy to use one's talents and concern for others.",
    audiences: ["graduate", "university"],
    subjects: ["humanities", "social-sciences", "economics", "medicine", "engineering", "environment"],
    goalSlugs: ["career-skills", "get-into-university", "start-research"],
    tags: ["Scholarship", "UK", "Oxford", "Fully funded"],
    eligibility: [
      "Apply through your eligible country or regional constituency",
      "Age and degree-completion requirements vary by constituency",
      "Applying for a full-time postgraduate degree at Oxford",
      "Constituency deadlines differ — check your own",
    ],
    country: "United Kingdom",
    location: "Oxford",
    format: "in_person",
    deadlineInDays: 63,
    cost: "Fully funded",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    isDemo: false,
    sourceNote: CONFIRM,
    prestige: 3,
  },

  // ──────────────────────── open to everyone / skills ─────────────────────

  {
    slug: "kaggle-competitions",
    title: "Kaggle Competitions",
    organization: "Kaggle (Google)",
    type: "competition",
    summary:
      "Open data science competitions you can enter today, with public leaderboards and shared solutions.",
    description:
      "Kaggle hosts machine learning competitions ranging from beginner-friendly tutorial contests to research problems with substantial prize pools. Because notebooks and solutions are shared publicly, it works as much as a learning resource as a competition, and a decent leaderboard placement plus a documented notebook is a genuine portfolio piece.",
    audiences: ["school", "university", "graduate"],
    subjects: ["data-science", "cs", "math"],
    goalSlugs: ["build-portfolio", "career-skills", "win-competitions", "find-internship"],
    tags: ["Competition", "Data science", "Remote", "Free", "Beginner friendly"],
    eligibility: [
      "Open to anyone with a free Kaggle account",
      "Age restrictions apply to prize-eligible competitions",
      "No institutional affiliation needed",
      "Beginner 'Getting Started' competitions run continuously",
    ],
    country: "Remote",
    location: "Online",
    format: "remote",
    deadlineInDays: null,
    cost: "Free",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://www.kaggle.com/competitions",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 1,
  },
  {
    slug: "google-cloud-certification",
    title: "Google Cloud Certification",
    organization: "Google Cloud",
    type: "certification",
    summary:
      "Recognised cloud credentials, from an entry-level Digital Leader to professional engineer tracks.",
    description:
      "Google Cloud offers a certification ladder starting with foundational credentials that need no hands-on experience and rising to professional-level exams for architects and engineers. Official learning paths and practice exams are published for each, making this one of the more legible ways to add a verifiable technical credential to a CV.",
    audiences: ["university", "graduate"],
    subjects: ["cs", "data-science", "engineering", "business"],
    goalSlugs: ["career-skills", "find-internship", "build-portfolio"],
    tags: ["Certification", "Cloud", "Remote", "Self-paced"],
    eligibility: [
      "Open to anyone — no formal prerequisites",
      "Foundational exams assume no hands-on experience",
      "Professional exams assume relevant industry experience",
      "Exam fee applies; scheduled online or at test centres",
    ],
    country: "Remote",
    location: "Online or test centre",
    format: "remote",
    deadlineInDays: null,
    cost: "Exam fee applies",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://cloud.google.com/learn/certification",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 1,
  },
  {
    slug: "freecodecamp-certifications",
    title: "freeCodeCamp Certifications",
    organization: "freeCodeCamp",
    type: "certification",
    summary:
      "Free, project-based web development and data science certifications — each requires five built projects.",
    description:
      "Each freeCodeCamp certification is earned by completing five required projects rather than by passing a quiz, which means finishing one leaves you with portfolio work as well as a credential. Tracks cover responsive web design, JavaScript algorithms, front-end libraries, data analysis with Python, and machine learning. Entirely free.",
    audiences: ["school", "university", "graduate"],
    subjects: ["cs", "data-science"],
    goalSlugs: ["career-skills", "build-portfolio", "find-internship"],
    tags: ["Certification", "Free", "Remote", "Project-based", "Beginner friendly"],
    eligibility: [
      "Open to anyone, any age",
      "Completely free including the certificate",
      "Each certification requires five completed projects",
      "Entirely self-paced",
    ],
    country: "Remote",
    location: "Online",
    format: "remote",
    deadlineInDays: null,
    cost: "Free",
    minGrade: 8,
    maxGrade: 12,
    officialUrl: "https://www.freecodecamp.org/learn/",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 1,
  },
  {
    slug: "un-volunteers-online",
    title: "UN Online Volunteering",
    organization: "United Nations Volunteers",
    type: "volunteer",
    summary:
      "Short remote volunteer assignments supporting UN agencies and NGOs — translation, research, design, development.",
    description:
      "The UN's online volunteering service lists remote assignments from UN agencies, governments and civil society organisations, covering tasks from translation and writing to data analysis, web development and graphic design. Assignments range from a few hours to several months and are open worldwide, which makes this one of the few internationally recognised opportunities with no location barrier.",
    audiences: ["university", "graduate", "school"],
    subjects: ["social-sciences", "environment", "humanities", "cs", "data-science", "medicine"],
    goalSlugs: ["career-skills", "build-portfolio"],
    tags: ["Volunteering", "Remote", "Free", "International", "Flexible"],
    eligibility: [
      "Aged 18 or over",
      "Open worldwide with internet access",
      "Assignments range from a few hours to several months",
      "Unpaid; UN certificate of participation provided",
    ],
    country: "Remote",
    location: "Online",
    format: "remote",
    deadlineInDays: null,
    cost: "Free (unpaid)",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://www.unv.org/become-online-volunteer",
    isDemo: false,
    sourceNote: ROLLING,
    prestige: 1,
  },

  // ─────────────────────────── illustrative examples ──────────────────────
  // Invented for the demo. Rendered with a "Demo example" badge and no apply
  // link so they are never presented as real programmes.

  {
    slug: "demo-regional-engineering-fair",
    title: "Regional Engineering Design Fair",
    organization: "Example Regional STEM Council",
    type: "competition",
    summary:
      "An illustrative local design competition, included to show how a regional qualifier appears in the feed.",
    description:
      "This is a demo entry, not a real programme. It stands in for the kind of regional competition that acts as a qualifier for larger national and international fairs — the sort of local opportunity a personalised feed should surface early, because it is usually the realistic first step towards something like ISEF. Search for an affiliated fair in your own region to find the real equivalent.",
    audiences: ["school"],
    subjects: ["engineering", "physics", "cs"],
    goalSlugs: ["win-competitions", "build-portfolio", "get-into-university"],
    tags: ["Demo example", "Competition", "Regional"],
    eligibility: [
      "Illustrative entry — eligibility shown for demo purposes only",
      "Typical regional fairs accept Grades 9–12",
      "Usually requires a project and a written summary",
      "Find your real affiliated regional fair via the ISEF site",
    ],
    country: "Demo",
    location: "Demo entry — no real location",
    format: "in_person",
    deadlineInDays: 3,
    cost: "Demo entry",
    minGrade: 9,
    maxGrade: 12,
    officialUrl: "https://www.societyforscience.org/isef/affiliated-fairs/",
    isDemo: true,
    sourceNote:
      "Illustrative example created for this demo. Not a real programme. The link goes to the official ISEF affiliated-fair directory, where real regional fairs can be found.",
    prestige: 1,
  },
  {
    slug: "demo-university-research-assistant",
    title: "Undergraduate Research Assistant Placement",
    organization: "Example University Department",
    type: "research",
    summary:
      "An illustrative departmental research placement, showing how a local university opening appears in the feed.",
    description:
      "This is a demo entry, not a real programme. It represents the most common and most overlooked research opportunity for university students: an unadvertised assistant position in a department at your own institution, usually obtained by emailing a professor whose work interests you. The Applications & CV course in Learn covers exactly how to write that email.",
    audiences: ["university"],
    subjects: ["physics", "biology", "cs", "data-science", "chemistry", "engineering"],
    goalSlugs: ["start-research", "find-internship", "career-skills"],
    tags: ["Demo example", "Research", "Local"],
    eligibility: [
      "Illustrative entry — eligibility shown for demo purposes only",
      "Typically second year onwards",
      "Usually arranged by contacting the professor directly",
      "Often unadvertised — email is the route in",
    ],
    country: "Demo",
    location: "Demo entry — no real location",
    format: "in_person",
    deadlineInDays: null,
    cost: "Demo entry",
    minGrade: null,
    maxGrade: null,
    officialUrl: "https://365step.local/learn/applications-and-cv/cold-outreach",
    isDemo: true,
    sourceNote:
      "Illustrative example created for this demo. Not a real programme. The link points to the 365step lesson on cold outreach, which is the actual method for finding placements like this.",
    prestige: 1,
  },
];
